### ISSUE TITLE
What is dpos.go for in IOST

### ISSUE THREAD

**Issue by jerkyrs** [iost-official/Go-IOS-Protocol#3]
What IS dpos.go for? IOST does not or should not rely on voted delegates for consensus implementing PoB instead?

https://github.com/iost-official/Go-IOS-Protocol/blob/eacf8d5565ca81e35261611b2f5e96b09e86e0dc/consensus/dpos/dpos.go

https://medium.com/@iostoken/iost-weekly-update-april-30th-may-7th-b0604c14e1d6

**Comment by tangky** [comment]
You are right that IOST is implementing a new consensus mechanism called PoB (Proof of Believability). As of now, the PoB source codes are under development and are in a private repository. 

As part of our research, we build a blockchain framework where we can test a variety of consensus including DPoS, PoW, as well as other consensus mechanisms and compare their performance. That's why you see dpos in our files.  

Thank you for your support. We are launching our testnet at the end of June and we look forward to your feedback.

**Comment by jerkyrs** [comment]
From my understanding of PoB vs DPoS i can see similarities in relation to votes (servi token) and possibly reviews depending on how this is implemented. One of the main issues with DPoS appears the votes exclude none delegates from becoming active block producers and are then not rewarded and may never be a delegate as a result of cartel style voting of existing delegates. I also do not see how this scales a network beyond delegates for running Dapps/Smart Contracts/storage etc.

If some form of delegation (believable league --> based on IOST balance, Servi balance, reviews) is used, it would be good to see forced rotation out of this league back to normal league. Do validators in normal league also get rewards and will they be used more generally for smart contract execution and Dapps? It seems fundamental to reward normal league as well as believable league.

The implementation of testnet with PoB and EDS components in Q2 will be impressive timeline to achieve IMHO.
